env:
  global:
    - CODACY_PROJECT_TOKEN=1e7b4b4611bc44c2b66e70d7eb64b5b1
language: node_js
node_js:
  - "8"
script:
  - npm run bundle
  - npm run unit
after_success:
  - cat ./test/unit/coverage/lcov.info | ./node_modules/.bin/codacy-coverage